version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3003:3000"
      - "3035:3035"
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
      - POSTGRES_HOST=chatwoot-postgres-1
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=ChatwootDBPass123!
      - POSTGRES_DB=chatwoot
      - REDIS_URL=redis://chatwoot-redis-1:6379
      - FRONTEND_URL=http://localhost:3003
    volumes:
      - .:/app
      - bundle_cache:/bundle
    command: bundle exec foreman start -f ./Procfile.dev
    networks:
      - chatwoot_default

volumes:
  bundle_cache:

networks:
  chatwoot_default:
    external: true